### ISSUE TITLE
Commits pushed by `EndBug/add-and-commit@v7` don't trigger push events on workflows of the same repository

### ISSUE THREAD

**Issue by israpps** [EndBug/add-and-commit#345] opened 2021-12-28 00:23 UTC

**Comment by EndBug** [comment] 2021-12-28 09:09
Duplicate of #188, and already answered [in the FAQs](https://github.com/EndBug/add-and-commit#the-commit-from-the-action-is-not-triggering-ci)

**Closed by EndBug** 2021-12-28 09:09 UTC
Labels: type: duplicate
