### ISSUE TITLE
insufficient permission for adding an object to repository database .git/objects

### ISSUE THREAD

**Issue by pfilourenco** [EndBug/add-and-commit#392] opened 2022-04-26 19:11 UTC
Hello,

Does anyone know how to resolve this error when this action tries to push commit?

`Error: Error: error: insufficient permission for adding an object to repository database .git/objects
error: modules/create_budget_alert/USAGE.md: failed to insert into database
error: unable to index file 'modules/create_budget_alert/USAGE.md'
fatal: updating files failed`

v9.0.0

**Comment by EndBug** [comment] 2022-04-26 19:41
Please add a link to the workflow you're using and the failed action run. If the repo you're having the issue is is private, please add a copy of the workflow and the logs of the step

**Comment by pfilourenco** [comment] 2022-04-27 08:26
> Please add a link to the workflow you're using and the failed action run. If the repo you're having the issue is is private, please add a copy of the workflow and the logs of the step

Workflow:
`  tf-docs:
    name: Create Tf docs for modules
    runs-on: ubuntu-latest
    #needs: ["tf-startup"]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.PAT_REPO }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4.4.0
        with:
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Render terraform docs for Modules inside the USAGE.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          find-dir: ./modules/
          output-method: replace
          git-push: false
          git-push-user-email: xxxx@xxxx
          git-push-user-name: xxxx
          output-file : USAGE.md
          template: |-
            
            {{ .Content }}
            
      - name: Add & Commit terraform docs
        uses: EndBug/add-and-commit@v9.0.0
        if: github.event_name == 'pull_request'
        with:
          # Arguments for the git add command
          add: "."
          #default_author: github_actions
          author_name: xxxx
          author_email: xxxx@xxxx
          committer_name: xxxx
          committer_email: xxxx@xxxx
          message: "terraform-docs automated action"
          push: true
`

Logs:
`Run EndBug/add-and-commit@v[9](https://github.com/nosportugal/terraform-aws-org/runs/6181630734?check_suite_focus=true#step:6:9).0.0
  with:
    add: .
    author_name: xxxx
    author_email: xxxx
    committer_name: xxxx
    committer_email: xxxx
    message: terraform-docs automated action
    push: true
    cwd: .
    default_author: github_actor
    pathspec_error_handling: ignore
    github_token: ***
  env:
    APPLY_FIXES: none
    APPLY_FIXES_EVENT: pull_request
    APPLY_FIXES_MODE: commit

Running in /home/runner/work/terraform-aws-org/terraform-aws-org
Add input parsed as single string, running 1 git add command.
> Using 'xxxx<xxxx@xxxx>' as author.
> Using custom committer info: nosgeadmin xxxx<xxxx@xxxx>
> Using "terraform-docs automated action" as commit message.
Internal logs
  > Staging files...
  > Adding files...
  Error: Error: error: insufficient permission for adding an object to repository database .git/objects
  error: modules/create_budget_alert/USAGE.md: failed to insert into database
  error: unable to index file 'modules/create_budget_alert/USAGE.md'
  fatal: updating files failed
  
Outputs
  committed: false
  commit_long_sha: undefined
  commit_sha: undefined
  pushed: false
  tagged: false
  tag_pushed: false
Error: Error: error: insufficient permission for adding an object to repository database .git/objects
error: modules/create_budget_alert/USAGE.md: failed to insert into database
error: unable to index file 'modules/create_budget_alert/USAGE.md'
fatal: updating files failed`

**Comment by lilithmooncohen** [comment] 2022-04-27 16:15
Seeing the same when using `terraform-docs/gh-actions`

**Comment by EndBug** [comment] 2022-04-27 17:23
It might be an issue with the file creation, since it seems that the error is caused by missing permissions in the folder...
To see if that's the case, you can try running the `git add` command manually and seeing if the error shows up anyways

**Comment by raiguard** [comment] 2022-05-22 20:50
This is happening to me as well.

Failed run: https://github.com/raiguard/krastorio-2/runs/6546149809?check_suite_focus=true
Workflow: https://github.com/raiguard/krastorio-2/blob/master/.github/workflows/crowdin.yml

This happened with `stefanzweifel/git-auto-commit-action` as well.

**Comment by EndBug** [comment] 2022-05-23 08:51
@raiguard Have you seen this comment? What happens when you run `git add`?

https://github.com/EndBug/add-and-commit/issues/392#issuecomment-1111276643

**Comment by raiguard** [comment] 2022-05-29 01:51
Running `git add .` results in the same thing.

I'm not bothered to fix it at this point, I'm moving all of my projects to Sourcehut and their CI is much simpler to work with. I think you can probably close this issue though, as it doesn't seem to be a problem with your action.

**Closed** 2022-05-29 08:54 UTC
Labels: type: question
