### ISSUE TITLE
Specify branch name

### ISSUE THREAD

**Issue by onilton** [EndBug/add-and-commit#29] opened 2020-04-30 20:05 UTC
On scheduled workflow it is not possible to run add-and-commit against a specific branch since it relies on  ${GITHUB_REF}.

schedule always use the last commit on default branch. 

```
on:
  schedule:
    - cron: "50 10,17,20,23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: gh-pages # a custom branch

    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        message: "Updated file"
        add: "file.csv"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I tried passing  `GITHUB_REF: refs/heads/gh-pages` in env, but it didn't work

**Comment by EndBug** [comment] 2020-04-30 20:20
Hi, thanks for the issue! Could you add a link to a workflow run that fails because of this? Just so that I can look at the logs...

**Comment by onilton** [comment] 2020-04-30 22:05
Sure.

https://github.com/onilton/deck-covid19/blob/fc968c33dedd4ef46b35921f52e6b8e38ed1fadd/.github/workflows/main.yml

**Comment by RobinWijnant** [comment] 2020-04-30 22:29
I see you are trying to deploy to Github pages. Other actions are more suitable for this.
This is a popular one for example: https://github.com/marketplace/actions/github-pages-action

**Comment by EndBug** [comment] 2020-05-01 08:43
> Sure.
> 
> https://github.com/onilton/deck-covid19/blob/fc968c33dedd4ef46b35921f52e6b8e38ed1fadd/.github/workflows/main.yml
> 
> But the one described above in the issue description is reduced and will probably also cause the issue.

Ok, I see where the problem is: I'll add a `ref` option where you can put the branch name, just like in `actions/checkout`

**Comment by EndBug** [comment] 2020-05-01 13:42
This should be fixed in version `v4.1.0` (which you can also get via the `v4` and `latest` tags)
You now have a `ref` option that you can use to select the branch you want to commit to.
Thanks for the issue!

**Closed by EndBug** 2020-05-01 13:42 UTC
Labels: enhancement, good first issue

**Comment by onilton** [comment] 2020-05-01 15:46
Cool! Nice work. Thanks! :clap:

**Comment by EndBug** [comment] 2020-07-10 15:15
@all-contributors please add @onilton  for ideas
